#  ATP Tennis Match Data Analysis (2020–2024)


## Introduction:
Tennis has evolved into a highly competitive and data-driven sport where match outcomes depend on multiple performance factors such as serving efficiency, player rankings, and match conditions. This project focuses on analyzing ATP Men’s Singles match data from 2020 to 2024 to uncover patterns and insights that define modern professional tennis.

The dataset includes match-level information from ATP tournaments across different surfaces, tournament categories, and competition rounds. It also contains player rankings and performance statistics such as aces, double faults, service points, break-point performance, and match duration.

Through Exploratory Data Analysis (EDA), this project aims to:

- Understand key performance metrics influencing match results  
- Identify trends in match competitiveness and duration  
- Analyze the impact of player rankings and seeding  
- Compare performance across different playing surfaces  
- Discover patterns that contribute to player success  

The insights generated from this analysis can help coaches, analysts, and tennis enthusiasts better understand performance strategies in modern ATP tennis.

DATASET OVERVIEW

Files Used:-

atp_matches_2020.csv

atp_matches_2021.csv

atp_matches_2022.csv

atp_matches_2023.csv

atp_matches_2024.csv

What each row represents-

Each row represents one ATP men’s singles match, including tournament context, player information, and detailed match statistics.

IMPORTING & READING THE DATA

We begin by importing the required libraries and reading the match data files. Since each file represents a different year but follows the same structure, we combine them into a single dataset for easier analysis.

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_2020 = pd.read_csv("/Users/ssweeti/Desktop/Tennis-project_EDA/tennis_atp-master/singles_matches/atp_matches_2020.csv")
df_2021 = pd.read_csv("/Users/ssweeti/Desktop/Tennis-project_EDA/tennis_atp-master/singles_matches/atp_matches_2021.csv")
df_2022 = pd.read_csv("/Users/ssweeti/Desktop/Tennis-project_EDA/tennis_atp-master/singles_matches/atp_matches_2022.csv")
df_2023 = pd.read_csv("/Users/ssweeti/Desktop/Tennis-project_EDA/tennis_atp-master/singles_matches/atp_matches_2023.csv")
df_2024 = pd.read_csv("/Users/ssweeti/Desktop/Tennis-project_EDA/tennis_atp-master/singles_matches/atp_matches_2024.csv")

Concating all files for Analysis

In [3]:
matches = pd.concat(
    [df_2020, df_2021, df_2022, df_2023, df_2024],
    ignore_index=True
)

In [4]:
matches.shape

(13174, 49)

In [5]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13174 entries, 0 to 13173
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          13174 non-null  object
 1   tourney_name        13174 non-null  object
 2   surface             13121 non-null  object
 3   draw_size           13174 non-null  int64
 4   tourney_level       13174 non-null  object
 5   tourney_date        13174 non-null  int64
 6   match_num           13174 non-null  int64
 7   winner_id           13174 non-null  int64
 8   winner_seed         5507 non-null   float64
 9   winner_entry        2028 non-null   object
 10  winner_name         13174 non-null  object
 11  winner_hand         13174 non-null  object
 12  winner_ht           13121 non-null  float64
 13  winner_ioc          13174 non-null  object
 14  winner_age          13172 non-null  float64
 15  loser_id            13174 non-null  int64
 16  loser_seed          3249 non-null   float64
 17  loser_entry         3029 non-null   object
 18  loser_name          13174 non-null  object
 19  loser_hand          13174 non-null  object
 20  loser_ht            13023 non-null  float64
 21  loser_ioc           13174 non-null  object
 22  loser_age           13171 non-null  float64
 23  score               13174 non-null  object
 24  best_of             13174 non-null  int64
 25  round               13174 non-null  object
 26  minutes             12300 non-null  float64
 27  w_ace               12627 non-null  float64
 28  w_df                12627 non-null  float64
 29  w_svpt              12627 non-null  float64
 30  w_1stIn             12627 non-null  float64
 31  w_1stWon            12627 non-null  float64
 32  w_2ndWon            12627 non-null  float64
 33  w_SvGms             12627 non-null  float64
 34  w_bpSaved           12627 non-null  float64
 35  w_bpFaced           12627 non-null  float64
 36  l_ace               12627 non-null  float64
 37  l_df                12627 non-null  float64
 38  l_svpt              12627 non-null  float64
 39  l_1stIn             12627 non-null  float64
 40  l_1stWon            12627 non-null  float64
 41  l_2ndWon            12627 non-null  float64
 42  l_SvGms             12627 non-null  float64
 43  l_bpSaved           12627 non-null  float64
 44  l_bpFaced           12627 non-null  float64
 45  winner_rank         13110 non-null  float64
 46  winner_rank_points  13110 non-null  float64
 47  loser_rank          13024 non-null  float64
 48  loser_rank_points   13024 non-null  float64
dtypes: float64(29), int64(6), object(14)
memory usage: 4.9+ MB

In [6]:
matches.head()
matches.tail()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
13169,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4,D,20240203,5,212051,NaN,NaN,...,30.0,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0
13170,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,1,122533,NaN,NaN,...,41.0,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0
13171,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,2,144748,NaN,NaN,...,51.0,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN
13172,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,4,122533,NaN,NaN,...,51.0,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0
13173,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,5,202475,NaN,NaN,...,53.0,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN

In [7]:
print(matches['tourney_date'].min())
print(matches['tourney_date'].max())

20200106
20241218

DATA CLEANING

In [8]:
matches.duplicated().sum()

np.int64(0)

In [9]:
missing_values = matches.isnull().sum().sort_values(ascending=False)

missing_values

winner_entry          11146
loser_entry           10145
loser_seed             9925
winner_seed            7667
minutes                 874
w_2ndWon                547
w_1stIn                 547
w_svpt                  547
w_df                    547
w_ace                   547
w_SvGms                 547
w_bpSaved               547
w_bpFaced               547
l_ace                   547
l_df                    547
l_svpt                  547
w_1stWon                547
l_1stIn                 547
l_1stWon                547
l_2ndWon                547
l_SvGms                 547
l_bpSaved               547
l_bpFaced               547
loser_ht                151
loser_rank              150
loser_rank_points       150
winner_rank              64
winner_rank_points       64
winner_ht                53
surface                  53
loser_age                 3
winner_age                2
tourney_id                0
round                     0
tourney_name              0
score                     0
loser_ioc                 0
loser_hand                0
loser_name                0
loser_id                  0
winner_ioc                0
winner_hand               0
winner_name               0
winner_id                 0
match_num                 0
tourney_date              0
tourney_level             0
draw_size                 0
best_of                   0
dtype: int64

Concated file for panda profiler

In [10]:
# df.to_csv("matches.csv", index=False)

In [14]:
matches['tourney_id'].nunique()

630

In [15]:
matches['tourney_id'].value_counts()[matches['tourney_id'].value_counts() > 1]

tourney_id
2021-520                               127
2024-520                               127
2022-520                               127
2021-540                               127
2023-560                               127
                                      ...
2023-M-DC-2023-FLS-M-SRB-GBR-01          2
2023-M-DC-2023-FLS-M-ITA-SRB-01          2
2023-M-DC-2023-FLS-M-ITA-NED-01          2
2023-M-DC-2023-FLS-M-FIN-AUS-01          2
2024-M-DC-2024-FLS-2-M-B-AUS-CZE-01      2
Name: count, Length: 630, dtype: int64

In [16]:
matches_copy = matches.copy()

In [ ]:
matches_copy.drop(columns=['winner_entry', 'loser_entry'], inplace=True)

In [ ]:
matches_copy.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_name,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2020-8888,Atp Cup,Hard,24,A,20200106,300,104925,NaN,Novak Djokovic,...,51.0,39.0,6.0,10.0,6.0,8.0,2.0,9055.0,1.0,9985.0
1,2020-8888,Atp Cup,Hard,24,A,20200106,299,105138,NaN,Roberto Bautista Agut,...,35.0,21.0,6.0,9.0,5.0,10.0,10.0,2335.0,34.0,1251.0
2,2020-8888,Atp Cup,Hard,24,A,20200106,298,104925,NaN,Novak Djokovic,...,57.0,35.0,25.0,14.0,6.0,11.0,2.0,9055.0,5.0,5705.0
3,2020-8888,Atp Cup,Hard,24,A,20200106,297,105583,NaN,Dusan Lajovic,...,54.0,39.0,14.0,12.0,0.0,1.0,34.0,1251.0,17.0,1840.0
4,2020-8888,Atp Cup,Hard,24,A,20200106,296,104745,NaN,Rafael Nadal,...,55.0,37.0,10.0,14.0,1.0,5.0,1.0,9985.0,18.0,1775.0

In [ ]:
matches_copy.tail()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_name,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
13169,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4,D,20240203,5,212051,NaN,Joaquin Aguilar Cardozo,...,30.0,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0
13170,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,1,122533,NaN,Nam Hoang Ly,...,41.0,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0
13171,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,2,144748,NaN,Kris Van Wyk,...,51.0,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN
13172,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,4,122533,NaN,Nam Hoang Ly,...,51.0,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0
13173,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,5,202475,NaN,Philip Henning,...,53.0,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN

In [ ]:
matches_copy.isna().sum().sort_values(ascending=False)

loser_seed            9925
winner_seed           7667
minutes                874
w_2ndWon               547
w_1stIn                547
w_svpt                 547
w_df                   547
w_ace                  547
w_SvGms                547
w_bpSaved              547
w_bpFaced              547
l_ace                  547
l_df                   547
l_svpt                 547
w_1stWon               547
l_1stIn                547
l_1stWon               547
l_2ndWon               547
l_SvGms                547
l_bpSaved              547
l_bpFaced              547
loser_ht               151
loser_rank             150
loser_rank_points      150
winner_rank             64
winner_rank_points      64
winner_ht               53
surface                 53
loser_age                3
winner_age               2
tourney_id               0
tourney_name             0
best_of                  0
score                    0
loser_ioc                0
loser_hand               0
loser_name               0
loser_id                 0
winner_ioc               0
winner_hand              0
winner_name              0
winner_id                0
match_num                0
tourney_date             0
tourney_level            0
draw_size                0
round                    0
dtype: int64

In [ ]:
matches_copy['winner_seed'] = matches_copy['winner_seed'].fillna('Unseeded')
matches_copy['loser_seed'] = matches_copy['loser_seed'].fillna('Unseeded')

In [ ]:
matches_copy.isna().sum().sort_values(ascending=False)

minutes               874
l_svpt                547
w_1stIn               547
w_df                  547
w_ace                 547
w_1stWon              547
w_2ndWon              547
w_SvGms               547
w_bpSaved             547
w_bpFaced             547
l_ace                 547
l_df                  547
w_svpt                547
l_1stIn               547
l_1stWon              547
l_2ndWon              547
l_SvGms               547
l_bpSaved             547
l_bpFaced             547
loser_ht              151
loser_rank            150
loser_rank_points     150
winner_rank            64
winner_rank_points     64
winner_ht              53
surface                53
loser_age               3
winner_age              2
tourney_id              0
tourney_name            0
best_of                 0
draw_size               0
tourney_level           0
tourney_date            0
match_num               0
winner_id               0
winner_seed             0
winner_name             0
winner_hand             0
winner_ioc              0
loser_id                0
loser_seed              0
loser_name              0
loser_hand              0
loser_ioc               0
score                   0
round                   0
dtype: int64

In [ ]:
matches_copy.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_name,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2020-8888,Atp Cup,Hard,24,A,20200106,300,104925,Unseeded,Novak Djokovic,...,51.0,39.0,6.0,10.0,6.0,8.0,2.0,9055.0,1.0,9985.0
1,2020-8888,Atp Cup,Hard,24,A,20200106,299,105138,Unseeded,Roberto Bautista Agut,...,35.0,21.0,6.0,9.0,5.0,10.0,10.0,2335.0,34.0,1251.0
2,2020-8888,Atp Cup,Hard,24,A,20200106,298,104925,Unseeded,Novak Djokovic,...,57.0,35.0,25.0,14.0,6.0,11.0,2.0,9055.0,5.0,5705.0
3,2020-8888,Atp Cup,Hard,24,A,20200106,297,105583,Unseeded,Dusan Lajovic,...,54.0,39.0,14.0,12.0,0.0,1.0,34.0,1251.0,17.0,1840.0
4,2020-8888,Atp Cup,Hard,24,A,20200106,296,104745,Unseeded,Rafael Nadal,...,55.0,37.0,10.0,14.0,1.0,5.0,1.0,9985.0,18.0,1775.0

In [ ]:
## match duration analysis (missing data filled with median)

matches_copy['minutes'].fillna(matches_copy['minutes'].median(), inplace=True)

/var/folders/n4/5mpnny3d2n5dqdtvgpbhfmdw0000gn/T/ipykernel_96346/3832806621.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  matches_copy['minutes'].fillna(matches_copy['minutes'].median(), inplace=True)

In [ ]:
## match statistsics columns missing data filled with 0 

stat_cols = [col for col in matches_copy.columns if col.startswith('w_') or col.startswith('l_')]

matches_copy[stat_cols] = matches_copy[stat_cols].fillna(0)

In [ ]:
## player heights data handle

matches_copy['winner_ht'].fillna(matches_copy['winner_ht'].median(), inplace=True)
matches_copy['loser_ht'].fillna(matches_copy['loser_ht'].median(), inplace=True)

/var/folders/n4/5mpnny3d2n5dqdtvgpbhfmdw0000gn/T/ipykernel_96346/1307709673.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  matches_copy['winner_ht'].fillna(matches_copy['winner_ht'].median(), inplace=True)
/var/folders/n4/5mpnny3d2n5dqdtvgpbhfmdw0000gn/T/ipykernel_96346/1307709673.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  matches_copy['loser_ht'].fillna(matches_copy['loser_ht'].median(), inplace=True)

In [ ]:
## winnner & loser rank points

matches_copy['winner_rank_points']= matches_copy['winner_rank_points'].fillna(0)
matches_copy['loser_rank_points']= matches_copy['loser_rank_points'].fillna(0)

In [ ]:
matches_copy.isna().sum()

tourney_id              0
tourney_name            0
surface                53
draw_size               0
tourney_level           0
tourney_date            0
match_num               0
winner_id               0
winner_seed             0
winner_name             0
winner_hand             0
winner_ht               0
winner_ioc              0
winner_age              2
loser_id                0
loser_seed              0
loser_name              0
loser_hand              0
loser_ht                0
loser_ioc               0
loser_age               3
score                   0
best_of                 0
round                   0
minutes                 0
w_ace                   0
w_df                    0
w_svpt                  0
w_1stIn                 0
w_1stWon                0
w_2ndWon                0
w_SvGms                 0
w_bpSaved               0
w_bpFaced               0
l_ace                   0
l_df                    0
l_svpt                  0
l_1stIn                 0
l_1stWon                0
l_2ndWon                0
l_SvGms                 0
l_bpSaved               0
l_bpFaced               0
winner_rank            64
winner_rank_points      0
loser_rank            150
loser_rank_points       0
dtype: int64

In [ ]:
matches_copy['surface'] = matches_copy['surface'].fillna(matches_copy['surface'].mode()[0])

In [ ]:
matches_copy['winner_age'] = matches_copy['winner_age'].fillna(matches_copy['winner_age'].median())

In [ ]:
matches_copy['loser_age'] = matches_copy['loser_age'].fillna(matches_copy['loser_age'].median())

In [ ]:
matches_copy.isna().sum()

tourney_id              0
tourney_name            0
surface                 0
draw_size               0
tourney_level           0
tourney_date            0
match_num               0
winner_id               0
winner_seed             0
winner_name             0
winner_hand             0
winner_ht               0
winner_ioc              0
winner_age              0
loser_id                0
loser_seed              0
loser_name              0
loser_hand              0
loser_ht                0
loser_ioc               0
loser_age               0
score                   0
best_of                 0
round                   0
minutes                 0
w_ace                   0
w_df                    0
w_svpt                  0
w_1stIn                 0
w_1stWon                0
w_2ndWon                0
w_SvGms                 0
w_bpSaved               0
w_bpFaced               0
l_ace                   0
l_df                    0
l_svpt                  0
l_1stIn                 0
l_1stWon                0
l_2ndWon                0
l_SvGms                 0
l_bpSaved               0
l_bpFaced               0
winner_rank            64
winner_rank_points      0
loser_rank            150
loser_rank_points       0
dtype: int64

In [ ]:
player_wins = (
    matches_copy.groupby("winner_name")
      .size()
      .reset_index(name="wins")
      .sort_values("wins", ascending=False)
)

In [ ]:
player_wins.head()

            winner_name  wins
241       Jannik Sinner   257
118     Daniil Medvedev   249
50        Andrey Rublev   246
487  Stefanos Tsitsipas   242
32     Alexander Zverev   241

In [ ]:
df.to_csv("matches_cleaned.csv", index=False)

In [ ]:
## seeded vs unseeded

df["winner_seeded"] = df["winner_seed"] > 0

seeded_wins = df["winner_seeded"].value_counts(normalize=True)

In [ ]:
serve_compare.head()

                         Winner Avg  Loser Avg
Aces                       6.757021   5.094808
Double Faults              2.439730   3.053514
First Serve Points Won    36.368681  32.627144
Second Serve Points Won   15.392667  13.958858

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Top 5 players overall
top_players = matches_copy["winner_name"].value_counts().head(5).index